<div id="content" class="span12"></div>

<script id="HeaderView" type="text/html">
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="/">BBCRUD - Backbone Testing</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="home-menu"><a href="/"><i class="icon-forward icon-white"></i> Home</a></li>
          <li class="add-menu"><a href="#index/add"><i class="icon-forward icon-white"></i> Add Customer</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="alert alert-success fade in">
  <a class="close" data-dismiss="alert" href="#"><span id="message-icon" class="icon-remove"></span></a>
  <h3 style="margin-top:5px;">System Message</h3> 
  <div class="message"></div>
  <p style="margin-top:15px;"><a class="btn" href="/">Return to menu.</a></p>
</div>
</script>

<style>
.nudge { margin-top:-0.6px; }
input.gridinput, select.gridinput {
	margin:0 5px 2px 0;
	line-height:0;
	width:90%;
	border:0;
	-webkit-border-radius: 1px;
}
td .btn-group {
	margin-top:2px;
	margin-left:2px;
}
tr th a:hover {
	text-decoration:none;
}
.table td {
	vertical-align: middle;
}
</style>

<script id="UserListView" type="text/html">
<table class="table table-hover table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <td colspan="7" class="lettering">
        <% _.each(characters, function(character) { %>
        <% var selected = (letter == character) ? ' letteron' : ''; %>
        <a href="/#index/letter/<%= character %>" class="sletters<%= selected %>" title="<%= character %>"><%= character %></a> 
        <% }); %>
      </td>
    </tr>
    <tr>
      <th style="width:200px;"><a href="#index/page/<%= _.escape(page || '1') %>/order/username/sort/<%= _.escape(sort || 'asc') %>">Username</a></th>
      <th style="width:200px;"><a href="#index/page/<%= _.escape(page || '1') %>/order/last_name/sort/<%= _.escape(sort || 'asc') %>">Customer Name</a></th>
      <th style="width:300px;"><a href="#index/page/<%= _.escape(page || '1') %>/order/email/sort/<%= _.escape(sort || 'asc') %>">Email Address</a></th>
      <th style="width:100px;"><a href="#index/page/<%= _.escape(page || '1') %>/order/identity/sort/<%= _.escape(sort || 'asc') %>">Identity</a></th>
      <th style="width:100px;"><a href="#index/page/<%= _.escape(page || '1') %>/order/verified/sort/<%= _.escape(sort || 'asc') %>">Verified</a></th>
      <th style="width:200px;"><a href="#index/page/<%= _.escape(page || '1') %>/order/created/sort/<%= _.escape(sort || 'asc') %>">Created</a></th>
      <th style="width:80px;">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><input type="text" class="input-small gridinput" name="username" id="data[username]" value="<%= _.escape(search.username || '') %>"></td>
      <td><input type="text" class="input-small gridinput" name="name" id="data[name]" value="<%= _.escape(search.name || '') %>"></td>
      <td><input type="text" class="input-small gridinput" name="email" id="data[email]" value="<%= _.escape(search.email || '') %>"></td>
      <td>
         <select name="identity" id="data[identity]" class="gridinput" style="width:130px;">
           <% _.each(_.extend({'-1':'Identity'}, identities), function(val, key) { %>
           <% var selected = (search.identity == key) ? 'selected="selected"' : ''; %>
           <option value="<%= key %>" <%= selected %>><%= val %></option>
           <% }); %>
         </select>
      </td>
      <td>
         <select name="verified" id="data[verified]" class="gridinput" style="width:110px;">
           <% _.each({'-1':'Verified', '1': 'Yes', '0': 'No'}, function(val, key) { %>
           <% var selected = (search.verified == key) ? 'selected="selected"' : ''; %>
           <option value="<%= key %>" <%= selected %>><%= val %></option>
           <% }); %>
         </select>
      </td>
      <td><input type="text" class="input-small gridinput datepicker" name="created" id="data[created]" value="<%= _.escape(search.created || '') %>"></td>
      <td>
        <div class="btn-group">
          <button id="grid-submit" data-loading-text="loading..." class="btn btn-mini" title="Submit Search"><i class="icon-refresh" style="margin-top:-1px;"></i> Filter</button>
          <button id="grid-reset" class="btn btn-mini dropdown-toggle" title="Reset Grid"><span class="icon-retweet" style="margin-top:-1px;"></span></button>
        </div>
      </td>
    </tr>
    <% var verifiedObject = {'1': 'Yes', '0': 'No'}; %>
    <% users.each(function(user) { %>
    <tr id="<%= _.escape(user.get('id') || '') %>" data-href="#index/edit/id/<%= _.escape(user.get('id') || '') %>" title="#index/edit/id/<%= _.escape(user.get('id') || '') %>">
      <td><%= _.escape(user.get('username') || '') %></td>
      <td><%= _.escape(user.get('first_name') || '') %> <%= _.escape(user.get('last_name') || '') %></td>
      <td><a href="mailto:<%= _.escape(user.get('email') || '') %>" title="Email: <%= _.escape(user.get('first_name') || '') %> <%= _.escape(user.get('last_name') || '') %> - <%= _.escape(user.get('email') || '') %>">[ <%= _.escape(user.get('email') || '') %> ]</a></td>
      <td><%= identities[_.escape(user.get('identity') || '')] %></td>
      <td><%= verifiedObject[_.escape(user.get('verified') || '')] %></td>
      <td><%= _.escape(user.get('created') || '') %></td>
      <td style="white-space:nowrap;text-align:right;vertical-align:middle;">
        <button class="btn btn-mini btn-primary" type="button" id="delete" title="Delete user"><i class="icon-ban-circle nudge"></i></button>
        <button class="btn btn-mini" type="button" id="view" title="View Profile"><i class="icon-camera nudge"></i></button>
      </td>
    </tr>
    <% }); %>
  </tbody>
</table>
</script>

<script id="PaginatorTemplate" type="text/html">
<% if(data.pageCount) { %>
<div class="dataTables_paginate paging_bootstrap pagination" id="jumping">
  <ul>
    <% if (data.previous) { %>
    <li class="prev"><a style="cursor:pointer;" href="#index/page/<%= data.first %>">First</a></li>
    <% } else { %>
    <li class="prev disabled"><a href="#">First</a></li>
    <% } %>
    <% if (data.previous) { %>
    <li><a style="cursor:pointer;" href="#index/page/<%= data.previous %>">&larr; Previous</a></li>
    <% } else { %>
    <li class="prev disabled"><a href="#">Previous</a></li>
    <% } %>
    <% Object.keys(data.pagesInRange).forEach(function(key) { %>
    <% var page = data.pagesInRange[key]; %>
    <li <% if(page == data.current) { %>class="active"<% } %>><a style="cursor:pointer;" href="#index/page/<%= page %>"><%= page %></a></li> 
    <% }); %>
    <% if (data.next) { %>
    <li class="next"><a style="cursor:pointer;" href="#index/page/<%= data.next %>">Next &rarr;</a></li>
    <% } else { %>
    <li class="next disabled"><a href="#">Next</a></li>
    <% } %>
    <% if (data.next) { %>
    <li class="next"><a style="cursor:pointer;" href="#index/page/<%= data.last %>">Last</a></li>
    <% } else { %>
    <li class="next disabled"><a href="#">Last</a></li>
    <% } %>
  </ul>
</div>
<% } %>
</script>

<script id="UserReviewView" type="text/html">
<h1>User Review View - <%= _.escape(email || '') %><h1>
</script>

<script id="UserModalView" type="text/html">
<div class="modal hide fade" id="user-form-modal">
  <div class="modal-header">
    <h3 id="modal-header">Add New User</h3>
  </div>
  <div class="modal-body" id="user-modal-body"></div>
  <div class="modal-footer">
    <button type="reset" data-dismiss="modal" class="btn btn-info">Close</button>
    <button type="submit" id="submit" data-loading-text="submitting..." class="btn btn-success">Submit</button>
  </div>
</div>
</script>

<script id="UserAddView" type="text/html">
<div class="modal hide fade" id="user-form-modal">
  <div class="modal-header">
    <h3 id="modal-header">Add New User</h3>
  </div>
  <div class="modal-body" id="user-modal-body">
    <form class="form-horizontal">
      <fieldset>
        <div class="control-group">
          <label class="control-label" for="username">Username:</label>
          <div class="controls">
            <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
              <input type="text" class="input-xlarge" id="username" name="username" value="<%= _.escape(username || '') %>">
              <p class="help-block">Please enter your desired username.</p>
            </div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="password">Password:</label>
          <div class="controls">
            <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
              <input type="text" class="input-xlarge" id="password" name="password" value="<%= _.escape(password || '') %>">
              <p class="help-block">Please enter your email address.</p>
            </div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="first_name">First name:</label>
          <div class="controls">
            <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
              <input type="text" class="input-xlarge" id="first_name" name="first_name" value="<%= _.escape(first_name || '') %>">
              <p class="help-block">Please enter your first name.</p>
            </div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="last_name">Last name:</label>
          <div class="controls">
            <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
              <input type="text" class="input-xlarge" id="last_name" name="last_name" value="<%= _.escape(last_name || '') %>">
              <p class="help-block">Please enter your last name.</p>
            </div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="email">Email address:</label>
          <div class="controls">
            <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
              <input type="text" class="input-xlarge" id="email" name="email" value="<%= _.escape(email || '') %>">
              <p class="help-block">Please enter your email address.</p>
            </div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="identity">Select identity:</label>
          <div class="controls">
            <select id="identity" name="identity">
              <% _.each(identities, function(val, key) { %>
              <% var selected = (identity== key) ? 'selected="selected"' : ''; %>
              <option value="<%= key %>" <%= selected %>><%= val %></option>
              <% }); %>
            </select>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="verified">Choose verified:</label>
          <div class="controls">
            <label class="checkbox inline">
              <input type="checkbox" id="verified" name="verified" value="0"> Yes
            </label>
            <label class="checkbox inline">
              <input type="checkbox" id="verified" name="verified" value="1" checked> No
            </label>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
  <div class="modal-footer">
    <button type="reset" data-dismiss="modal" class="btn btn-info">Close</button>
    <button type="submit" id="submit" data-loading-text="submitting..." class="btn btn-success">Submit</button>
  </div>
</div>
</script>

<script id="UserEditView" type="text/html">
<form class="form-horizontal">
  <input type="hidden" name="id" value="<%= _.escape(id || '') %>">
  <fieldset>
    <div class="control-group">
      <label class="control-label" for="username">Username:</label>
      <div class="controls">
        <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
          <input type="text" class="input-xlarge" id="username" name="username" value="<%= _.escape(username || '') %>">
          <p class="help-block">Please enter your desired username.</p>
        </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="password">Password:</label>
      <div class="controls">
        <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
          <input type="text" class="input-xlarge" id="password" name="password" value="">
          <p class="help-block">Please enter your email address.</p>
        </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="first_name">First name:</label>
      <div class="controls">
        <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
          <input type="text" class="input-xlarge" id="first_name" name="first_name" value="<%= _.escape(first_name || '') %>">
          <p class="help-block">Please enter your first name.</p>
        </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="last_name">Last name:</label>
      <div class="controls">
        <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
          <input type="text" class="input-xlarge" id="last_name" name="last_name" value="<%= _.escape(last_name || '') %>">
          <p class="help-block">Please enter your last name.</p>
        </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="email">Email address:</label>
      <div class="controls">
        <div class="input-prepend"> <span class="add-on"><i class="icon-home"></i></span>
          <input type="text" class="input-xlarge" id="email" name="email" value="<%= _.escape(email || '') %>">
          <p class="help-block">Please enter your email address.</p>
        </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="identity">Select identity:</label>
      <div class="controls">
        <select id="identity" name="identity">
          <% _.each(identities, function(val, key) { %>
          <% var selected = (identity== key) ? 'selected="selected"' : ''; %>
          <option value="<%= key %>" <%= selected %>><%= val %></option>
          <% }); %>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="verified">Choose verified:</label>
      <div class="controls">
        <label class="checkbox inline">
          <input type="checkbox" id="verified" name="verified" value="0" <% if(verified == 1) { %><%= 'checked' %><% } %>> Yes
        </label>
        <label class="checkbox inline">
          <input type="checkbox" id="verified" name="verified" value="1" <% if(verified == 0) { %><%= 'checked' %><% } %>> No
        </label>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="created">Create date:</label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-home"></i></span><input type="text" class="input-xlarge" id="created" name="created" value="<%= _.escape(created || '') %>">
          <p class="help-block">Length must be between 3 and 20 characters.</p>
        </div>
      </div>
    </div>
  </fieldset>
</form>
</script>

<script id="ProfilerView" type="text/html">
<table class="table table-striped table-bordered table-condensed profiler">
  <thead>
    <tr>
      <th style="text-align: center; width:5%;">Count</th>
      <th style="text-align: left; width:80%;">&nbsp;SQL Statement</th>
      <th style="text-align: center; width:15%;">Time</th>
    </tr>
  </thead>
  <tbody>
    <% _.each(data.queries, function(query) { %>
    <tr>
      <td style="text-align: center;"><%= _.escape(query.count || '') %>.</td>
      <td><%= _.escape(query.query || '') %></td>
      <td><i><%= _.escape(query.seconds || '') %></i></td>
    </tr>
    <% }); %>
  </tbody>
</table>
<table class="table table-striped table-bordered table-condensed profiler">
  <thead>
    <tr>
      <th style="width: 85%">&nbsp;Statistic</th>
      <th style="text-align: center; width: 15%">Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Total milliseconds:</td>
      <td><%= _.escape(data.elapsed_milliseconds || '') %></td>
    </tr>
    <tr>
      <td>Average query time:</td>
      <td><%= _.escape(data.average_query_time || '') %></td>
    </tr>
    <tr>
      <td>Queries per second:</td>
      <td><%= _.escape(data.queries_per_second || '') %></td>
    </tr>
    <tr>
      <td>Longest query time:</td>
      <td><%= _.escape(data.longest_query_time || '') %></td>
    </tr>
    <tr>
      <td>Longest query id:</td>
      <td>#<%= _.escape(data.longest_query_id || '') %>.</td>
    </tr>
  </tbody>
</table>
</script>
