<!doctype html>
<html>
<head>
  <title>Jasmine Spec Runner</title>
  <link rel="shortcut icon" type="image/png" href="/javascripts/tests/lib/jasmine-1.3.1/jasmine_favicon.png">
  <link rel="stylesheet"  href="/javascripts/tests/lib/jasmine-1.3.1/jasmine.css">
  <script data-main="/javascripts/tests/SpecRunner.js" src="/javascripts/lib/require-2.1.2.js"></script>
</head>
<body>
	<div id="sandbox" style="overflow: hidden; height: 1px;"></div>
</body>
</html>
