<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>Micro Framework Quick Start</title>
<link href="/stylesheets/application.css" rel="stylesheet">
</head>
<body>

<div class="header"></div>

<div class="container">

  <div class="row-fluid">
    <?php echo $this->layout()->content ?>
  </div>

  <footer class="footer">
    <p class="pull-right"></p>
    <p><a href="http://tomshaw.info/" target="_blank">Backbone.js</a> Testing Application.</p>
  </footer>
</div>

<script src="/javascripts/vendor/jquery-1.8.3.js"></script> 
<script src="/javascripts/vendor/underscore-1.4.3.js"></script> 
<script src="/javascripts/vendor/backbone-0.9.2.js"></script>
<script src="/javascripts/vendor/bootstrap.js"></script> 
<?php echo $this->inlineScript(); ?>
</body>
</html>