<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>BBCRUD - Backbone (C)reate (R)ead (U)pdate (D)elete</title>
<link href="/stylesheets/smoothness/jquery-ui-1.9.2.custom.css" rel="stylesheet">
<link href="/stylesheets/application.css" rel="stylesheet">
<?php echo $this->headScript() ?>
</head>
<body>

<div class="header"></div>

<div class="container">
  <div class="row-fluid"> 
    <div id="content" class="span12">
      <?php echo $this->layout()->content ?> 
    </div>
  </div>
  <footer class="footer">
    <p><a href="http://tomshaw.info/" target="_blank">Backbone.js</a> Testing Application.</p>
  </footer>
  <div id="profiler"></div>
</div>

<?php echo $this->placeholder('templates') ?>

<script src="/javascripts/vendor/jquery-1.8.3.js"></script> 
<script src="/javascripts/vendor/jquery-ui-1.9.2.min.js"></script> 
<script src="/javascripts/vendor/handlebars-1.0.rc.1.js"></script> 
<script src="/javascripts/vendor/underscore-1.4.3.js"></script> 
<script src="/javascripts/vendor/backbone-0.9.9.js"></script> 
<script src="/javascripts/vendor/bootstrap.js"></script> 
<script src="/javascripts/utils.js"></script> 
<?php echo $this->inlineScript(); ?>

</body>
</html>